### ISSUE TITLE
沙发哟

### ISSUE THREAD

**Issue by Seven-Liang** [lingochamp/LingoRecorder#4]
您好 请教您个问题  看您项目里用MediaCodec进行了音频转码  想问下用这种硬解的方式会不会存在兼容性的问题  谢谢

**Comment by rantianhua** [comment]
硬解的方式是有兼容性的问题的，主要取决于设备是否支持你想使用的编码器，所以如果想自己用编码器硬编硬解，需要检查设备是否支持特定的编码器，检查可参考 [列出设备的编码器列表](https://developer.android.com/reference/android/media/MediaCodecInfo.html) 。

**Comment by Seven-Liang** [comment]
您是英语流利说的吗？
