### ISSUE TITLE
请问录制的声音很小

### ISSUE THREAD

**Issue by SL-Y** [lingochamp/LingoRecorder#5]
请问录制的声音很小，有什么办法播放的时候让其声音大些。我将录制下来的文件打开。声音太小了

**Comment by rantianhua** [comment]
录制声音时是你设备的麦克风采集的，它采集的分贝是多少就是多少，如果你指的是播放的音量，那你在播放的时候将音量调大就好了。你所说的“打开文件，声音太小”具体是什么场景？比如，你录的声音本来就很小吗？播放的时候手机音量是不是就很小？

**Comment by rantianhua** [comment]
@wuketidai

**Comment by rantianhua** [comment]
你可以将 PCM 的数据都乘上一个倍数来增大音量，具体见：http://blog.csdn.net/timsley/article/details/50683084
