### ISSUE TITLE
录出来的flac有问题

### ISSUE THREAD

**Issue by hankooxiaozei** [lingochamp/LingoRecorder#6]

**Comment by wuketidai** [comment]
demo 里面 AndroidFlacProcessor 采用 mediaCodec 进行编码，编码的是音频流，最终并未生成 header 所以通用播放器是无法播放的。
如果你想要通用播放器可以播放，你可以在 start() 中生成 header，当最后编码完毕在更新 header 即可

**Comment by hankooxiaozei** [comment]
我这里想编码成aac 也要这样吗
