### ISSUE TITLE
您好，请问下我通过MediaCodec在您的demo上转码为aac

### ISSUE THREAD

**Issue by SL-Y** [lingochamp/LingoRecorder#7]
但是录制得到的文件自带的播放器播放声音很奇怪，尖锐的听不清的

**Comment by rantianhua** [comment]
请问你的采样率是多少？

**Comment by SL-Y** [comment]
采样率是160000，我也尝试改为441000，但是有bug。难道是采样率的问题？

**Comment by rantianhua** [comment]
是的，目前已经发现了采样率的一个bug，正在修复中。aac 的转码问题我们也会尽快测试的。

**Comment by rantianhua** [comment]
sorry，这么久才回复，1.2.1-SANPSHOT版本已经修正了采样率的bug，请尝试用这个版本，然后看看你转的 aac 还有问题吗？

**Comment by rantianhua** [comment]
我用 1.2.1 的版本试过了没有问题了，你也可以用最新版本试一下。有问题欢迎再来反馈！
